### PR TITLE
Add direct links to measure charts

### LINKED ISSUE #1227: Add link to bookmark/share link for individual measures within a page
I propose we add a "Share this" or "Copy link to clipboard" at the bottom of each measure, eg. present Url (which may be CCG, practice or England page) plus `/#[measurename]`.

E.g. as a user I might be looking at the all-england page and see the Opioids measure half way down the page - I want to share this specific measure with someone / on social media, link to it in a paper/blog, or bookmark it for later. However all I can see is the url for the whole page (https://openprescribing.net/all-england/) or a link to breakdown by CCG. 

The average user wouldn't know the short measure name to allow them to do it manually, and it would help us if this were listed on the page as well, so we don't need to remember or look up the short measure name. 

image

Marking as trivial as I think this would be pretty easy! But I may be wrong.

### PR DESCRIPTION
**Pull request by evansd**
We already supported this, but there was no easy way to find out the
correct link for a given chart. This patch adds the link into the panel
heading for each chart and, as an extra usability feature, clicking the
link temporarily replaces it with a text input with the link text
already selected and copies it to the clipboard (where the browser
supports that).

Closes #1227

Screenshot before clicking:
192 168 1 127_8000_ccg_02n_measures__tags eye 2

Screenshot after clicking:
192 168 1 127_8000_ccg_02n_measures__tags eye 1

### CODE REVIEW

**Comment by evansd** [comment]
We could also make the link be automatically copied to the clipboard when the user clicks, but I haven't done this as that gives me a slightly icky feeling. I'd be open to changing my mind on that though if people thought it would be a big usability benefit.

**Comment by sebbacon** [comment]
I think we *should* copy to the clipboard, because it's consistent with [what we do elsewhere](https://github.com/ebmdatalab/openprescribing/commit/c3fe6207641060260872d12409b3cad264c3a92a), icky or not!

One other thought - should we perhaps link to (a version of) the "breakdown by component" page instead of the chart itself? https://openprescribing.net/ccg/99P/ace/. The thing where we shade out all the other measures on a page is cute, but it is also a pretty horrible UI experience if someone's first interaction with the site involves a freezy-loady-75+measures page. Linking to the "by component" means a fast load, plus the opportunity to see other detailed info about the measure on one page (which we could build on in the future - list of "other measures in same categories", for example.

Doing this would also require a couple of extra changes to the "by component" page to make it a more generic "one-measure-view page":

* "Presentations contributing to variation" should be moved below the chart
* That section should also be hidden for measures without the ability to show presentations (q.v. @inglesp's current work)
* Make the "View all measures for X CCG" link more prominent, more like a main navigation element
* I note a bug on that page whereby the text describing total possible savings for all measures appears - which it shouldn't

Thoughts?  @HelenCEBM @evansd ?

**Comment by evansd** [comment]
OK, happy to implement the copy-to-clipboard thing.

I totally agree that our current measure highlighting thing is not great UX and I think your suggestion makes a lot of sense. (I'm assuming you actually meant this URL: https://openprescribing.net/measure/ace/ccg/99P/).

I think we should park this PR temporarily and make a separate issue and PR to improve the breakdown page along the lines you suggest.

**Comment by HelenCEBM** [comment]
good idea, i forgot that the chart was on that page. Should work well with tweaks as described!

**Comment by inglesp** [comment]
One problem with this: not every measure can be broken down by presentation, so we'll have to remove the "Presentations contributing to variation" table in this case.  (Should be easy -- just check `measure.numerator_can_be_queried`.)

And example is https://openprescribing.net/measure/bdzadq/ccg/99P/ which will be fixed (see #1203) but new measures, eg GBGs, may not.

**Comment by evansd** [comment]
This is parked until all #1380 is completed, at which point it can be merged without further work.

**Pull request merged**
