### PR TITLE
Creation of 17 NHSE low priority measures

### PR DESCRIPTION
**Pull request by richiecroker**

### CODE REVIEW

**Comment by sebbacon** [comment]
@richiecroker  - FYI all measures must end in `.json` - I'll fix this.

**Comment by sebbacon** [comment]
@richiecroker, I have just noticed the denominator descriptions are wrong for a number of the measures ([e.g. this one](https://github.com/ebmdatalab/openprescribing/blob/af16dc0489a485be5b711ddce8b8dad4e748f8bb/openprescribing/frontend/management/commands/measure_definitions/lptravelvacs#L14)); they all say "1000 patients" where some should be per section or subsection or whatever.

**Comment by richiecroker** [comment]
@seb, they should all be per 1000 patients.

**Comment by sebbacon** [comment]
This is now ready for review on staging.  Things to think about
* [ ] Precise wording for omnibus measure TBC, including how to describe the numerator / denominator
* [ ] Is the `sum(all_numerators)/sum(all_denominators)` approach correct? (I think so)
* [ ] Layout of CCG page. It's getting quite noisy with "labs", alert signups, and now this (screenshot below).  Ideas? 

image

**Comment by lmfrench** [comment]
Add it as a tab where it says 'sort prescribing measures by' ? And add a sentence to the 'labs' page part instead of it being a separate blue box?

**Comment by sebbacon** [comment]
For the layout issues, I'm going to do something "good enough" and propose a significant upgrade per #567 soon.

**Pull request merged**
