### PR TITLE
Update lptramadolpara.json

### PR DESCRIPTION
**Pull request by richiecroker**
amended SQL and text

### CODE REVIEW

**Comment by chrisjwood16** [comment]
Just trying to understand the SQL with this. It seems to give 2 duplicate BNF codes (040702040AAAUAU, 040702040AABCBC) - does this risk double counting? Changing "UNION ALL" to "UNION DISTINCT" seems to fix it?

**Comment by chrisjwood16** [comment]
Actually this doesn't seem to be working - preview shows zeros all round:
https://openprescribing.net/measure/preview_lptramadolpara/
vs
https://openprescribing.net/measure/lptramadolpara/

**Comment by chrisjwood16** [comment]
> Actually this doesn't seem to be working - preview shows zeros all round: https://openprescribing.net/measure/preview_lptramadolpara/ vs https://openprescribing.net/measure/lptramadolpara/

Fixed - needed to change "numerator_bnf_codes_filter" to "numerator_bnf_codes_query"

**Review by chrisjwood16 — APPROVED** [review]

**Comment by richiecroker** [comment]
thanks for fixing that @chrisjwood16

**Pull request merged**
