### PR TITLE
amended view

### PR DESCRIPTION
**Pull request by richiecroker**
have changed view to remove homeopathy items

### CODE REVIEW

**Comment by richiecroker** [comment]
this can go straight to production.  Ta!

**Comment by inglesp** [comment]
You'll need to add the SQL for `vw__median_price_per_unit`.

* Add `vw__herbal_list.sql` in `openprescribing/frontend/management/commands/measure_sql/`.  (Compare with eg [`vw__median_price_per_unit.sql`](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/management/commands/measure_sql/vw__median_price_per_unit.sql).)
* Add `"vw__herbal_list"` to the list of views [here](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/pipeline/management/commands/create_bq_measure_views.py#L30-L40).

Give a shout if that doesn't make sense!

**Comment by richiecroker** [comment]
`vw__median_price_per_unit` or `vw__median_price_per_unit`?

**Comment by inglesp** [comment]
`vw__herbal_list`!

**Comment by richiecroker** [comment]
done!

**Pull request merged**
