### PR TITLE
Add ability for end users to download data

### LINKED ISSUE #58: Re-add link to download raw data on analyse chart, add modal
Ben wants this, so we know who's using the data and can ensure we get credit in papers etc.

### PR DESCRIPTION
**Pull request by sebbacon**
Fixes #58 (though without modal)

### CODE REVIEW

**Comment by sebbacon** [comment]
Currently works in IE10 and IE11 but not IE9.

**Comment by frabcus** [comment]
Is IE9 a requirement generally for these sites? Commonly enough used in the 
NHS?

In recent years, I've tended to only support IE11 as that is only one 
supported by Microsoft.

Francis

**Comment by richiecroker** [comment]
According to Google Analytics 3.2% of visitors to our site are using IE8, and 1.98% are using IE9.  So only about 1 in 20.

**Comment by sebbacon** [comment]
It may be that within the NHS we do need to support older IEs. See #371 for different stats.

**Comment by sebbacon** [comment]
Per an update I just made to #371, it is likely that up to 10% of NHS users are using IE8/9. Given these are a core target group, I don't think we can just ignore them completely.

**Comment by sebbacon** [comment]
Closing this PR in favour of #453

**Pull request closed without merging**
