### PR TITLE
Update items, quantity, actual cost definitions in FAQs

### PR DESCRIPTION
**Pull request by evansd**
The aim is for these to be slightly easier to understand by the interested layperson.

Existing text:
openprescribing net_faq_

New text:
localhost_8000_faq_

### CODE REVIEW

**Comment by HelenCEBM** [comment]
Looks good to me! Do we have an explainer on ADQs? Under the issue of adding quantities we could refer people to that if so.

**Comment by evansd** [comment]
Doesn't look like we do have anything on ADQs at the moment, but we should add something once we have decent quality ADQ data in the site (I think there are still some pieces to get in place before we can do that).

**Comment by evansd** [comment]
@richiecroker Would appreciate a quick once over on this just to make sure I haven't accidentally said something subtly wrong.

**Comment by richiecroker** [comment]
Looks good.

A couple of points:

1.  I think we could simply the item definition further by removing "single" and "regular"
2.  Under quantity, we need to have a definition for inhalers: Where the formulation is inhalers the quantity is usually the number of inhalers.

**Comment by evansd** [comment]
@richiecroker Why "_usually_ the number of inhalers"? Do we know what the exceptions are? Or do we just want to say: "... but there are occasionally inconsistencies here so exercise caution when analysing this data"

**Comment by richiecroker** [comment]
inhalers are the slight nightmare.  There was one in particular (@sebbacon will remember it) which was inconsistent in it's coding.  I think I want to say "but there are occasionally inconsistencies here so exercise caution when analysing this data"

**Pull request merged**
