### PR TITLE
Style simplification

### PR DESCRIPTION
**Pull request by sebbacon**
* Drop background wallpaper

### CODE REVIEW

**Comment by sebbacon** [comment]
## Before
before

## After
after

**Comment by HelenCEBM** [comment]
I like the no-background, but I'd say the fonts look a bit too standard and boring....

**Comment by Bengoldacre** [comment]
is this to improve consistency on different browsers (system fonts) or just for the look of it? slight preference for original fonts but no strong feelings.

**Comment by sebbacon** [comment]
It is generally just for the look of it -- there was a discussion at a team meeting recently -- but it does have performance benefits too.

The main change requested was the background.

**Comment by sebbacon** [comment]
Updated just to remove background image for the time being.

**Pull request merged**
