### PR TITLE
Update semagglutidequantity.json

### PR DESCRIPTION
**Pull request by brianmackenna**
This is a slightly temporary fix for #2939 . I have included all the possible variations of tabs/caps, this might be slightly overkill and there are nicer ways of fixing but this is most time efficient I think!

### CODE REVIEW

**Comment by richiecroker** [comment]
this looks fine, although we might come a cropper again if liquid specials start appearing.

One alternative may be to have

```
bnf_code LIKE '0601023AW%' --Semaglutide
AND
bnf_name  LIKE '% inj %'
```

**Comment by madwort** [comment]
nb @brianmackenna I think it might not be your change that's the problem with CI, will look into it when I can

**Comment by madwort** [comment]
rebased to add the ansible CI fix

**Comment by richiecroker** [comment]
@brianmackenna just thinking about this again - the code won't work, as you'll need `bnf_code NOT LIKE...AND` rather than `OR`
I've amended the code to just include `%inj%` which seems to work in tests.

**Review by richiecroker — CHANGES_REQUESTED** [review]
I've reviewed and made further changes to code as per comments.  Can you review please @brianmackenna

**Review by brianmackenna — COMMENTED** [review]
This looks good  and much simpler solution than initially proposed. Thanks!

**Comment by richiecroker** [comment]
@inglesp can you merge this please - @brianmackenna and I are both happy.

**Review by inglesp — APPROVED** [review]

**Pull request merged**
