### PR TITLE
Stop using third-party hosted assets, where possible

### PR DESCRIPTION
**Pull request by evansd**
Doing so leads to issues like #1645 (i.e. mysterious breakages for some
users) and given that we host everything via Cloudflare's CDN there's no
performance advantage.

We make an exception for the Mapbox assets, because we're dependent on
their tile server anyway for the maps to work.

We also don't bother vendoring those files only loaded for IE8 as the
site is pretty much unusable on IE8 anyway.

### CODE REVIEW

**Comment by sebbacon** [comment]
Great drive-by fixage!

One comment / query: can we obviate the risk of referring to a file that hasn't been vendored?

I'm hand-waving as it's part of the django machinery I don't know much about, but it looks like ManifestStaticFilesStorage might help here?

**Comment by evansd** [comment]
Fortunately that's handled for us automatically: when DEBUG is false the `static` template tag will blow up loudly if you reference a file that's not in the manifest.

Just re-running the tests which terminated due to Travis flakiness.

**Comment by sebbacon** [comment]
It it worth running a functional test or two with `DEBUG=False` as part of our suite?

**Comment by evansd** [comment]
Well the issue here (which came up when I first introduced ManifestStaticFilesStorage in #1510) is that we're not using the same storage backend in test. This is Django's recommended way of working around the fact that `collectstatic` isn't run by default during test setup, and that Django won't serve your static files for you if DEBUG is False. But I don't think it's a great solution.

It's possible to run with the same config in production and test if we start using WhiteNoise, but I didn't want to foist my pet project on you without being sure there was a need first.

**Comment by sebbacon** [comment]
OK!

**Comment by evansd** [comment]
Happy to merge as is? I can create a separate ticket for updating our test set up.

**Comment by sebbacon** [comment]
yes!

**Pull request merged**
