### PR TITLE
Use current CCG membership in presentations by practice API query

### PR DESCRIPTION
**Pull request by inglesp**
This will fix the chart at https://openprescribing.net/analyse/#org=practice&orgIds=14L&numIds=0703021Q0BB&denom=nothing&selectedTab=chart

This has no new tests -- updating the test fixtures is too much work as it breaks lots of other tests

### CODE REVIEW

**Comment by sebbacon** [comment]
Genuine test error:

```
======================================================================
ERROR: test_spending_by_practice_on_multiple_presentations (frontend.tests.test_api_spending.TestSpendingByPractice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/openprescribing/frontend/tests/test_api_spending.py", line 530, in test_spending_by_practice_on_multiple_presentations
    rows = self._get_rows(params)
<snip>
ProgrammingError: column pc.pct_id does not exist
LINE 13: ... pr.presentation_code LIKE '0202010B0AAABAB') AND pc.pct_id ...
                                                              ^
HINT:  Perhaps you meant to reference the column "pr.pct_id".
```

I agree with the hint - although it could also be `pc.code`, but I that would *probably* result in a less performant query.


I also just spotted this in the test output, not sure how long that's been going on:

```
Traceback (most recent call last):
  File "./scripts/wait_for_postgres.py", line 16, in <module>
    host=environ['DB_HOST'],
  File "/usr/local/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'DB_HOST'
```

**Comment by inglesp** [comment]
Gah, amateur hour!  Have fixed by changing `.pct_id` to `.ccg_id`.  (In my defence, it is a *bit* confusing...)

**Comment by sebbacon** [comment]
Per my concern about performance, this query has conditions on two different tables. It is likely to be more performant (as it could use one index) to apply compound conditions to the largest table first, i.e. against `pr` rather than `pc`.

I've not given this masses of thought so might be wrong. Would at least be a good idea to try out on staging before merging, if you've not already done so, and compare performance.

**Comment by sebbacon** [comment]
I am starting to review outstanding issues properly in the issue tracker, and noticed what I think describes this problem [here](https://github.com/ebmdatalab/openprescribing/issues/408#issuecomment-305133917) - worth reviewing to check you agree they're the same issue and that this PR would fix that issue

**Comment by inglesp** [comment]
Have benchmarked the queries, and the new query is faster (~520ms vs ~750ms, best of three).  The `EXPLAIN` output is 231 rows and so I haven't dug into why!

You're right that [this comment](https://github.com/ebmdatalab/openprescribing/issues/408#issuecomment-305133917) and #479 are related.  They will be fixed in some cases by this PR, and in other cases by #846 (which is merged but we haven't done an import since the merge), depending on whether the analysis is for chemicals or presentations.

**Comment by sebbacon** [comment]
I'm happy if you want to merge & deploy then

**Comment by inglesp** [comment]
Before:

image


After:

image

**Pull request merged**
