### PR TITLE
remove "get in touch re data"

### PR DESCRIPTION
**Pull request by richiecroker**
Amending text on site to remove offers of extracting data

### CODE REVIEW

**Comment by evansd** [comment]
This was deliberately left in by @HelenCEBM in her changes here:
https://github.com/ebmdatalab/openprescribing/pull/3428/files#diff-2d2bde7ccb25d9ff729d40c0757e76ec43871d18aa3da713601c2b57b5263987

I don't have a view on this myself, but just wanted to make sure the two of you had coordinated.

**Comment by HelenCEBM** [comment]
I took out the bit specifically referring to custom extracts but left in the possibility to answer questions or set up collaborations for now as I wasn't aware that had changed... But happy for it to be taken out if this no longer applies

**Review by evansd — APPROVED** [review]

**Comment by richiecroker** [comment]
not to be merged until Bennett Institute name change confirmed!

**Comment by richiecroker** [comment]
@morleyjr can you take a look at the PR for the ["about" page](https://github.com/ebmdatalab/openprescribing/blob/remove_data_extract_text/openprescribing/templates/about.html) to check the funders statement please?

**Review by brianmackenna — APPROVED** [review]

**Pull request merged**
