### PR TITLE
Revert "Ensure data is in BQ before downloading it"

### PR DESCRIPTION
**Pull request by inglesp**
Reverts ebmdatalab/openprescribing#2612

This causes the e2e tests to fail.

### CODE REVIEW

**Comment by evansd** [comment]
Isn't it a problem of some kind if there isn't any practice stats data in BQ when the end-to-end tests run?

**Comment by inglesp** [comment]
> Isn't it a problem of some kind if there isn't any practice stats data in BQ when the end-to-end tests run?

We don't have five years of data for the end-to-end tests to use, so this assert gets hit.

**Comment by evansd** [comment]
Ah of course, this is a month-by-month check rather than a check over the entire five years.

I still feel like this is a useful check as it would have saved us on a couple of occasions recently. I'd be more in favour of adding a setting like `ALLOW_EMPTY_PRACTICE_STATISTICS` which is False by default but True in the end-to-end tests.

I can try to find a bit of time to do this if you're deep in the middle of [_the other thing_] (it's hard to remember which of our communication channels are public sometimes!).

**Comment by inglesp** [comment]
Good idea.  Closing in favour of #2653.

**Pull request closed without merging**
