### PR TITLE
Flag up Closed/Dormant practices on the frontend

### LINKED ISSUE #889: Label dormant / closed practices
In the list of practices at the top of a CCG page([example](https://openprescribing.net/ccg/08C/)), and at the top of a Practice page ([example](https://openprescribing.net/practice/E85124/)), we should clearly label Closed and Dormant practices as such (with the word "Closed" or "Dormant").

In analyses, where someone is searching for organisations the practice name should also indicate "(closed)" or "(dormant)".  

Presumably a safe way of doing this is to add it to the generated title of a practice.

It may be worth linking somewhere to [our explanation of "dormant"](https://ebmdatalab.net/what-is-a-dormant-gp-practice-and-why-are-they-prescribing/) if it's possible to do discreetly.

For further background, see #215 and #522.

The current status is stored in our Practice model.

### PR DESCRIPTION
**Pull request by evansd**
Closes #889

### CODE REVIEW

**Comment by evansd** [comment]
Now deployed to staging, see e.g.
http://staging.openprescribing.net/practice/A89038/
http://staging.openprescribing.net/practice/B84614/
http://staging.openprescribing.net/practice/

In trying to test my changes to the Analyse page I've discovered that the search only returns active practices in any case so my changes here are redundant. See:
https://github.com/ebmdatalab/openprescribing/blob/24110f5a190eab8bc5d01e235fb2de812980913d/openprescribing/api/views_org_codes.py#L53

Should I back them out? Or should we change the search to return dormant practices now that we can flag them as such in the results?

**Comment by sebbacon** [comment]
I think we should back them out.

How we handle closed/dormant practices is still [an ongoing discussion](https://github.com/ebmdatalab/openprescribing/issues/891), but I believe @richiecroker's preference has always been that we should merge historic data about closed practices into the surviving practice, if we can. 

If it turns out this is possible, then analyses should always be against current practices (just as we always treat their CCG membership as always having pertained to their current membership), meaning we should filter out closed/dormant practices there (but still keep them on CCG / Practice index pages).

If it's not possible, we can always revisit this PR. 

Once that's backed out, happy to merge.

**Comment by sebbacon** [comment]
Some more thoughts on exploring further.

Two other places we should consider adding the status:

1. It would be nice for it to appear in the page `<title>` (thus in search engines)
2. [This measures page](http://staging.openprescribing.net/ccg/02T/nebivolol/) image

Per my previous comment, it's probable that point (2) will become irrelevant when we resolve practice mergers, but that may take some time, so it's worth doing for now, I think.

Finally, the "what does this mean" link only pertains to **dormant** practices. We probably don't need to explain what "closed" means.

**Comment by evansd** [comment]
@sebbacon I've updated this PR to address the various points you raised. I can't deploy it to staging at the moment though because it's being used to asses the new measures.

**Comment by evansd** [comment]
Deployed to staging now. See:
http://staging.openprescribing.net/ccg/11X/ciclosporin/#L85045 (scroll up a bit)
http://staging.openprescribing.net/practice/L85602/

**Pull request merged**
