### PR TITLE
Update lpbathshoweremollients.json

### PR DESCRIPTION
**Pull request by richiecroker**
added in QV gentle wash

### CODE REVIEW

**Review by inglesp — APPROVED** [review]
Code change is fine.  Let me know when you'd like this merged/deployed.

**Comment by richiecroker** [comment]
@brianmackenna can you review quickly please and then we can merge.  Ta!

**Review by brianmackenna — APPROVED** [review]

**Comment by CarolineMorton** [comment]
@richiecroker can we merge this?

**Comment by richiecroker** [comment]
yes, not sure why it hasn't!

**Pull request merged**
