### PR TITLE
Add explanatory text on Drug Tariff search page

### LINKED ISSUE #684: Suggested wording for tariff viewer
The Drug Tariff is the "NHS primary care price list" for thousands of the most commonly-prescribed drugs, and is updated monthly.  Sometimes medicines go out-of-stock, and a "price concession" is given so that pharmacists having to buy more expensive versions are not out of pocket.  
Search to view a medicine's Drug Tariff price and category, and whether it has had a price concession.  Our data goes back to March 2010.  Drug Tariff data is updated as the latest month is released (usually three days before it is active).  Price concession data is updated daily!

### PR DESCRIPTION
**Pull request by evansd**
Closes #684

I've slightly reordered the paragraphs so that the "Search" call to
action comes directly before the search input which made more sense to
me.

I've also made it so that the text doesn't appear if there's already a
search query set, the reason being that it's quite a lot of text and if
you already know what you're looking at it's probably more distracting
than helpful. But happy to take other opinions on that.

### CODE REVIEW

**Comment by HelenCEBM** [comment]
Can we put a link to the main data source @richiecroker ? (I was looking for it to put in our presentation next week and hoped I'd find it here!)

**Comment by sebbacon** [comment]
Good suggestion @HelenCEBM.  @evansd: can we add something like "([source](http://psnc.org.uk/dispensing-supply/supply-chain/generic-shortages/ncso-archive/))"

**Comment by evansd** [comment]
@sebbacon Is that the source for both the monthly tariff data and the daily price concession data? From the page title it looks like just the price concession data. Is there a separate source for the tariffs?

**Comment by richiecroker** [comment]
Tariff data comes from here @HelenCEBM https://www.nhsbsa.nhs.uk/pharmacies-gp-practices-and-appliance-contractors/drug-tariff

**Comment by richiecroker** [comment]
Out of interest, despite the NHSBSA telling me in an FOI request that they didn't have it, we can now get DT data back to 2002.  Do we want to add it, or is there no need...

**Comment by HelenCEBM** [comment]
We should also link people back to @richiecroker 's [blog](https://ebmdatalab.net/getting-the-data-for-the-drug-tariff-tool-sigh/) on how he pulled the data together, and perhaps point to the blogs that add up the impact of the price concessions?

**Comment by evansd** [comment]
@HelenCEBM Something like this?

> Read more about the challenges involved in <a href="https://ebmdatalab.net/getting-the-data-for-the-drug-tariff-tool-sigh/">getting this data</a>, and our <a href="https://ebmdatalab.net/tag/price-concessions/">regular reviews</a> on the impact of price concessions.

**Comment by evansd** [comment]
OK, well maybe I'll deploy what we've got now (i.e. just with links to the source data) and we can add another para with blog links later. Just pop something in a github issue whenever you're ready.

**Pull request merged**
