### PR TITLE
Create bdzadq.json

### PR DESCRIPTION
**Pull request by richiecroker**
This is a beta version of a proposed benzodiazepine measure.

### CODE REVIEW

**Comment by evansd** [comment]
@richiecroker These are now up on the staging site:
http://staging.openprescribing.net/measure/

(Note, I had to fix a couple of [missing spaces](https://github.com/ebmdatalab/openprescribing/pull/892/commits/74ba0112ca4a180b7366e970997b8b66736aea81) in the numerator definition.)

**Comment by evansd** [comment]
This is blocked while we resolve the wider issue with ADQs.

**Comment by evansd** [comment]
@richiecroker You're writing SQL under literally the hardest circumstances I ever seen anyone write it: broken up into bits in a JSON file with an execution time somewhere between 45 minutes and a week depending on when a developer next gets to it. So I wouldn't beat yourself up about it :)

**Comment by sebbacon** [comment]
By the way I expect to have a fixed ADQ table uploaded by today

**Comment by sebbacon** [comment]
I'm going to leave deploying this until ADQ data is deployed (hopefully today) and then alter the query to use the new (hopefully correct!) ADQ data.

**Comment by inglesp** [comment]
These are now on staging at http://staging.openprescribing.net/measure/bdzadq/ and http://staging.openprescribing.net/measure/bdzper1000/.

Will wait for input from @sebbacon before deploying to production.

**Comment by sebbacon** [comment]
@richiecroker I think we can now use our own ADQs table rather than maintaining one manually?

i.e. replace the reference here:

https://github.com/ebmdatalab/openprescribing/blob/d9fbf1950a8f59994a28eaabbddc2425dd2ff940/openprescribing/frontend/management/commands/measure_definitions/bdzadq.json#L27

with something like this:

https://github.com/ebmdatalab/openprescribing/blob/f649c39b5c3d3eee472b6eef29a5f867219ccc3a/openprescribing/frontend/management/commands/measure_definitions/ktt9_uti_antibiotics.json#L33-L35

**Comment by evansd** [comment]
Merged into #1081

**Pull request closed without merging**
