### PR TITLE
Automated deployments

### PR DESCRIPTION
**Pull request by sebbacon**
Support automated deploys from the command line.

This PR includes resetting our migrations so we can confidently rely on migrations that have been checked into the source code from now on (and can confidently automate running migrations as part of a deploy).

Therefore, before merging this branch, it should be deployed to staging with:

    fab deploy:staging,branch=deployment

And then we should run the following to ensure the production database thinks its migrations are fully up to date:
  
    cd /webapps/openprescribing_staging
    echo "DELETE FROM django_migrations" | python manage.py dbshell --settings=openprescribing.settings.production
    python manage.py migrate --fake

Finally, it should be safe to merge this PR, then deploy with 

    fab deploy:production

### CODE REVIEW

**Comment by sebbacon** [comment]
@annapowellsmith, the bits that need your attention (for Cloudflare) are marked with `XXX` in `fabfile.py`.

As an aside, for the staging server to be browseable, we need to set up DNS so that `staging.openprescribing.net` is a CNAME for `openprescribing.net`. (It is protected with Basic WWW auth, credentials in `pass`). For the time being I have the following in my `/etc/hosts`:

    46.101.62.45    staging.openprescribing.net

**Comment by sebbacon** [comment]
Also note [the new environment variables](https://github.com/ebmdatalab/openprescribing/pull/29/commits/94a78c11613771da097a83a6a59f4343dc007394) required for the cloudflare part of the deploy process.

**Comment by annapowellsmith** [comment]
Please could we have some documentation (in gdrive) about how we do deploys / migrations under this new regime?

**Comment by sebbacon** [comment]
What do you feel is missing from [the README](https://github.com/ebmdatalab/openprescribing/pull/29/files#diff-04c6e90faac2675aa89e2176d2eec7d8)? I tried to cover it all there. Should I update that and mention it in gdrive, or create it only in gdrive and mention that in the README?

**Comment by annapowellsmith** [comment]
Ah no that's perfect thanks - just didn't spot it!

**Comment by sebbacon** [comment]
After deply, we should also rebuild the Travis docker image

**Comment by annapowellsmith** [comment]
I think we need `Fabric==1.11.1` in `requirements/local.txt`.

**Comment by annapowellsmith** [comment]
I ran `fab deploy:staging,branch=deployment` and saw `Fatal error: No changes to pull from origin! Aborting.`. I continued on the assumption that that was OK, and was able to run the migrations successfully :)

**Comment by sebbacon** [comment]
Great!

That error message was because I'd previously deployed that branch, so it was bailing early. You can use the `force_build` option to proceed in any case.  So, when you say "I continued" -- do you mean you did `force_build`, or something else?

Also -- re running the migrations successfully -- if you were doing `deploy:staging`, it shouldn't have done any migrations. Or do you mean you manually did the migrations on production?

**Comment by annapowellsmith** [comment]
re "I continued" - I had a look on the server at the git status, saw that it seemed to be up to date, and continued on to the migrations. Didn't do anything else. 

Re running the migrations, I followed your instructions after "And then we should run the following", so I think that's a yes, I manually did the migrations on production.

**Comment by annapowellsmith** [comment]
I've now run a snapshot on production FYI. So we could try deploying...

**Comment by annapowellsmith** [comment]
Please could you put the basic-auth password for the site in pass?

**Comment by sebbacon** [comment]
It's already in there..?

**Comment by sebbacon** [comment]
(or at least, when I do `git pass push` it claims it's "up-to-date")

**Comment by annapowellsmith** [comment]
Ah sorry so it is! Didn't see it below my commits.

**Pull request merged**
