### PR TITLE
Add .python-version file

### PR DESCRIPTION
**Pull request by madwort**
* test whether this will persuade dependabot to use the correct version
* 3.8.6 because that appears to be what is currently used in production

### CODE REVIEW

**Review by evansd — APPROVED** [review]
Worth a shot!

**Comment by madwort** [comment]
@evansd what's worrying me about this one is that I have no idea whether it'll affect the production deployment...

**Comment by evansd** [comment]
A valid concern, but it won't have any effect in this case.

**Comment by madwort** [comment]
Great, it's worked - first unblocked PR here: https://github.com/ebmdatalab/openprescribing/pull/2969 
Now to fix https://github.com/ebmdatalab/openprescribing/issues/2959 ...

**Pull request merged**
