### PR TITLE
Import shorter BNF codes

### LINKED ISSUE #81: Don't reject presentations with BNF codes shorter than 15 chars
In our `import_bnf_codes` script we reject presentations with BNF codes that are shorter than 15 chars. 

However, some devices seem to have presentation codes of less than 15 chars. For example:

21010220113    Flutter Oscillating Positive Expiratory Pressure Dev   
21010220114   Acapella Oscillating Positive Expiratory Pressure Dev   

These are legitimate so we should not exclude them.

### PR DESCRIPTION
**Pull request by sebbacon**
Closes #81 
Examples include dressings, ileostomy bags, etc

### CODE REVIEW

**Comment by annapowellsmith** [comment]
Have you tried running this with the BNF dataset? We may make assumptions elsewhere in the codebase about the length of BNF codes.

**Comment by sebbacon** [comment]
Yes, as in, a full dataset imports directly, but that only exercises the script and the models; is there anything else I should be running?

**Comment by annapowellsmith** [comment]
It's just odd that I've explicitly written a test to ensure that product codes are always 15 characters. I can't see any assumptions about it elsewhere in the codebase, but it would be good just to run a few searches, check out the dashboards etc, and be sure it doesn't break anything.

**Comment by sebbacon** [comment]
Yes, it is odd isn't it - that's why I've described  the shape of the data in #81 in case it gives any insights. Which it didn't ;)

It's hard for me to do anything that feels like an exhaustive test on my development box as I don't have so much data ingested.

Now I understand the data better, perhaps I should invest some time in generating a representative dataset for development...

**Comment by annapowellsmith** [comment]
Can you run searches for these products on the analyse page on your dev box, and see the correct data in the front-end? If so, I'll merge.

**Comment by sebbacon** [comment]
Tested and happy with it.

**Pull request merged**
