### PR TITLE
Update lpamiodarone.json

### PR DESCRIPTION
**Pull request by richiecroker**

### CODE REVIEW

**Comment by chrisjwood16** [comment]
It mentions "is in line with NICE Guidance CG180" (taken from NHS E website) - but on checking this was replaced in 2021 by [NG196](https://www.nice.org.uk/guidance/ng196). Presume we should reference/link to the appropriate guidelines.

**Comment by richiecroker** [comment]
> 

@chrisjwood16 my view is that we are quoting "NHS England states"...  there are a lot of issues with their wording, and if we try and correct we'll tie ourselves in knots, as these things aren't mentioned in later NICE guidelines.  I've got a list that I will email them with, but let's use their wording for now

**Comment by chrisjwood16** [comment]
> > 
> 
> @chrisjwood16 my view is that we are quoting "NHS England states"... there are a lot of issues with their wording, and if we try and correct we'll tie ourselves in knots, as these things aren't mentioned in later NICE guidelines. I've got a list that I will email them with, but let's use their wording for now

Ah just pushed an update. They do link to the correct guidance further down, so think it's justified here to put correct link?

**Comment by richiecroker** [comment]
we're going to come across this time after time - they are often referring to (@brianmackenna 's?) original work here, so as we're quoting I suggest we stick with what they're saying

**Review by chrisjwood16 — APPROVED** [review]

**Pull request merged**
