### PR TITLE
Add task to create public measure tables in BQ

### PR DESCRIPTION
**Pull request by inglesp**
The tables created are already in the `public_draft` dataset.

### CODE REVIEW

**Comment by inglesp** [comment]
> Is there an argument for making these views? Mainly pedagogic - users can see how they have been constructed

I think that the SQL is too overwhelming to be much use pedagogically.  Better is to document carefully, like [this](https://openprescribing.net/docs/querying-the-raw-data-yourself/).

Also, it makes querying the table significantly slower.

**Comment by inglesp** [comment]
> Have you already sanity checked that this produces the same output as our main code 

Yes, it does, more or less.

The difference is when a practice has zero for both its numerator and its denominator in a given month.  In OpenPrescribing, we treat set `calc_value` and `percentile` to `NULL`.  Here, we set `ratio` and `percentile` to `0`.

This makes more sense in some situations (eg if a practice prescribes no Levetiracetam, then it makes sense to say that its ratio of Keppra to Levetiracetam is zero)...

...and less in others (eg if a practice is closed and has no prescribing and no patients, it makes sense to say that doesn't have a ratio.

Another effect on this change is shift, slightly, the percentile values for all practices.  That is: the OpenPrescribing method calculates the percentiles over all practices with non-`NULL` ratios, while this method calculates the percentiles over all practices.  This means that percentile values here differ slightly from those on the website.

Thoughts?

**Comment by sebbacon** [comment]
OK - I suggest documenting this in the excellent documentation already produced. i.e. "you can query measure data here but note it differs very slightly from the data on openprescribing in the following ways"?

**Comment by inglesp** [comment]
Have updated the docs.

**Pull request merged**
