### PR TITLE
Create nitrofurantoin

### PR DESCRIPTION
**Pull request by richiecroker**
Can we deploy to the staging site for testing please

### CODE REVIEW

**Comment by sebbacon** [comment]
@richiecroker  says:

> If we can do it, we should make this a bespoke one, and get traffic to our site from MO teams.
> Whereby we show them both their baseline figure, and their target as lines on the graph, so they can see if they are achieving.

It wouldn't be *too* hard, but how would we set the baseline? Just as of this month?

Prob 1 - 2 days work max.

**Comment by richiecroker** [comment]
as per the documentation: https://www.england.nhs.uk/wp-content/uploads/2015/12/ann-b-qual-prem.pdf
> a 10% reduction (or greater) in the Trimethoprim: Nitrofurantoin prescribing ratio based on CCG baseline data (June15-May16) for 2017/18. In 2018/19 reduction thresholds will be reviewed to ensure targets reflect latest activity and maximise appropriate reduction gains

**Comment by richiecroker** [comment]
Here's one I mocked up in Google Sheets:
https://docs.google.com/spreadsheets/d/1xwALNjLBysSetwlRdlBbhn0vYVGw6ztoAcHuaIqV2sY/edit?usp=sharing

**Comment by richiecroker** [comment]
so, next question is, can we make it more useful for users, by from April 17 showing the performance in that year?

i.e. for April 17 show April 17 data
for May 17 show sum(april and may)
etc...

**Comment by sebbacon** [comment]
Closing this as it will require more work (have captured it as an issue for later triage).

Unless you want me to do it as a standard measure until then @richiecroker?

**Pull request closed without merging**
