### PR TITLE
new_measure__amox_500_15_caps.json

### PR DESCRIPTION
**Pull request by richiecroker**

### CODE REVIEW

**Comment by richiecroker** [comment]
Preview measure here: https://openprescribing.net/measure/preview_amox_500_15_caps/

**Comment by brianmackenna** [comment]
Looks good - are there any obvious conditions we can think of that have >5 days course recommended. It would be good to hint that it might not be realistic to get this to 0% - I think it reads like that now.

**Comment by richiecroker** [comment]
@chrisjwood16 I don't think the "title" field actually does anything...

**Comment by chrisjwood16** [comment]
> @chrisjwood16 I don't think the "title" field actually does anything...

Ah, couldn't work out what was missing, but felt weird to leave it as "title"!

**Comment by chrisjwood16** [comment]
> Looks good - are there any obvious conditions we can think of that have >5 days course recommended. It would be good to hint that it might not be realistic to get this to 0% - I think it reads like that now.

I've added in H. pylori treatment as an example of where higher doses/longer courses might be used.

**Review by chrisjwood16 — APPROVED** [review]

**Pull request merged**
