### PR TITLE
Update CCG boundaries and fix import

### PR DESCRIPTION
**Pull request by evansd**
This updates the test fixture to use the latest CCG boundaries, obtained using [this script](https://github.com/ebmdatalab/fetch-boundaries/tree/2a9d0f711a81c1dbe68ba4874071545256b98c14).

It also fixes the import so that it updates the org models in-place rather than replacing them and contains some workarounds for a nasty [GDAL incompatibility](https://github.com/ebmdatalab/openprescribing/issues/3263).

### CODE REVIEW

**Review by ghickman — APPROVED** [review]
All looks sensible 👍

**Comment by sebbacon** [comment]
Great. Is there somewhere we could make some nice public acknowledgements for the NHSX pals who helped out here?

**Comment by sebbacon** [comment]
Also I think the whole docstring in the management commands describing the manual rigmarole could be replaced by a link to that fetcher script?

**Comment by evansd** [comment]
> Is there somewhere we could make some nice public acknowledgements for the NHSX pals who helped out here?

Yes, happy to but not sure where. I'll update the original issue once this is deployed and the boundaries imported.

**Pull request merged**
