### PR TITLE
Improve spending charts with sparse data

### LINKED ISSUE #71: Fix design of BNF charts with sparse data
This sort of chart isn't helpful: 

https://openprescribing.net/chemical/0604012V0

Either return a bunch of zeroes in the data, or (better?) hard-code the x-axis to start at August 2010 and end at the current date.

### PR DESCRIPTION
**Pull request by sebbacon**
This PR pads out spending histogram data with zeros for months where there is no data.

That makes charts with very sparse data more comprehensible.

Closes #71

### CODE REVIEW

**Comment by annapowellsmith** [comment]
Sorry to be a pain, but could 26165df8cb06f1b6099b1d54008d24e8d76b1e35 be a separate PR? My brain is too small to deal with non-atomic PRs.

**Comment by sebbacon** [comment]
Oh, sorry, it was meant to be in its own branch - fat finger. I'll sort tomorrow.

**Comment by sebbacon** [comment]
I'd not branched off master. Rebased and force-pushed.

**Comment by annapowellsmith** [comment]
So for me this change breaks `/analyse` - I see `openprescribing.js:36861 Uncaught TypeError: this.value.substring is not a function`. Does it still work for you?

**Comment by sebbacon** [comment]
Yes it does. Did you run migrations?

**Comment by annapowellsmith** [comment]
Yes I did. Hmmmm. Can you render e.g. http://localhost:8000/analyse/#org=CCG&numIds=0604012V0&denomIds=6.4.1&selectedTab=summary locally on this branch without an error?

**Comment by sebbacon** [comment]
Closing this in favour of filling sparse data only for spending totals, per narrower definition in original issue

**Pull request closed without merging**
