### PR TITLE
Support selecting analysis panel via URL

### PR DESCRIPTION
**Pull request by sebbacon**
**Support selecting analysis panel via URL**
This allows people to bookmark maps and time series.

### CODE REVIEW

**Comment by sebbacon** [comment]
Closes #10

**Comment by annapowellsmith** [comment]
Needs rebase? Also needs the minified JS file I'm afraid.

**Comment by annapowellsmith** [comment]
Looks good! Tested cross-browser. The only nitpicky change I might make is instead of `data-target` we could just use the `href` attribute, since we have to have the `href` for Bootstrap tabs anyway. (For some reason GitHub won't let me leave a line note.)

**Comment by sebbacon** [comment]
See 6126f28b0e5f5086dfc8d6f40c6e731541fda2bf for a (slightly unsatisfactory) explanation of why we are using data-target

**Comment by annapowellsmith** [comment]
Ah OK! Merging 😸

**Pull request merged**
