### PR TITLE
Bmk update to injectable abx

### PR DESCRIPTION
**Pull request by brianmackenna**

### CODE REVIEW

**Comment by inglesp** [comment]
Let me know when you have the "why it matters".

**Comment by brianmackenna** [comment]
Ah it was in a commit comment that don't seem to easily pull through

unsure where it goes in new measure def structure. to do: we need to exclude 
`bnf_code NOT LIKE "0501070I0%"

why it matters is [here on this google doc](https://docs.google.com/document/d/1DNJoMsNfCv4CIHR3Xo7p9AtQjnwknskPY1_glpqUsXg/edit)

**Comment by inglesp** [comment]
> Ah it was in a commit comment that don't seem to easily pull through

I missed that.  It's hidden behind the `...`:

image

Will update the definition.

**Comment by inglesp** [comment]
I've updated the PR, and it's on staging at http://staging.openprescribing.net/measure/injectable_antibiotics/ccg/00K/.

**Comment by inglesp** [comment]
I've committed some stray files, sorry.  Will sort out later.

**Pull request merged**
