### PR TITLE
Ensure dropdowns work on documentation pages

### LINKED ISSUE #219: Fix drop down for 'Trends' and 'More'  on top bar when on help document page
The drop down menus for 'trends' and 'more' don't work if you are on one of the help document pages - if you click them nothing happens, makes it difficult to navigate the site. The other links on the top bar all work fine.

example:
https://openprescribing.net/docs/analyse/#

### PR DESCRIPTION
**Pull request by sebbacon**
Fixes #219

### CODE REVIEW

**Comment by annapowellsmith** [comment]
Looks good! Out of interest though, could we not just use openprescribing.js in the same way as other pages? The user will presumably have it cached, so although it's a bigger, may not be less efficient, and would mean we could get rid of some code.

**Comment by sebbacon** [comment]
Yeah, I guess you're right. I'll change it...

**Comment by sebbacon** [comment]
ping @annapowellsmith

**Comment by annapowellsmith** [comment]
Hooray!

**Pull request merged**
