### PR TITLE
Show when entities are closed on their homepage

### PR DESCRIPTION
**Pull request by inglesp**
Practice:

image
 
Regional team:

image

### CODE REVIEW

**Comment by inglesp** [comment]
This fixes part of #889.

**Comment by HelenCEBM** [comment]
Can we make the text stand out a bit more? e.g. "CLOSED: 16 May 2018" or use red maybe?

**Comment by inglesp** [comment]
Here it is wrapped in a `<span class="text-danger">`.

image

What do you think @HelenCEBM?

**Comment by HelenCEBM** [comment]
Yes great thanks!

**Comment by inglesp** [comment]
>  In case you've not noticed, you appear not to have pushed the red styling.

Pushed now.

**Comment by evansd** [comment]
:+1: Looks good to me

**Pull request merged**
