### PR TITLE
Dockerise the app

### PR DESCRIPTION
**Pull request by sebbacon**
The purpose of this PR is to support running the tests in a docker container, as a workaround for problems we had getting the software to build in the Travis environment.

Theoretically this should allow us to run tests faster, and longer term, run a staging server using the same principles.

The PR also includes fixes to tests to get the test suite to pass.

### CODE REVIEW

**Comment by annapowellsmith** [comment]
Yay Docker!

In general I'd prefer https://github.com/ebmdatalab/openprescribing/pull/17/commits/aa33bc0c3a09bef9cf5ce190fc5831daed232736 as a separate PR, but doesn't matter this time. All v odd - odd that it passes for me even though the filepath is wrong, and odd that `test_convert_hscic_prescribing.py` fails for you, even though it's a file you're creating.

**Comment by sebbacon** [comment]
I've squashed the many commits that made up the docker-specific part of this PR into [one commit](6f409497e0dc999068e04bd7aad3ed4e931a5cc4) to make a tidy commit history.

I've moved the failing tests to a separate branch, for which I'll make a PR shortly.

This PR is ready for a final review and merge. The Travis tests are expected to fail as I've removed the fixes to the aforementioned tests.

**Comment by sebbacon** [comment]
Fixes #18

**Comment by annapowellsmith** [comment]
Hooray!

**Pull request merged**
