### PR TITLE
added hyperlinks to paper

### PR DESCRIPTION
**Pull request by richiecroker**

### CODE REVIEW

**Comment by inglesp** [comment]
@richiecroker do you want this reviewed and merged?

**Comment by richiecroker** [comment]
@inglesp not sure why I didn't respond to this, yes please!

**Comment by evansd** [comment]
Ah, I see. Yeah, you want a `<br>` for that as the text appears in different contexts.

**Comment by richiecroker** [comment]
ok, what's current status of this, i'll make a change.

**Comment by evansd** [comment]
Although actually, on reflection, even that wouldn't be great. The layout's only been designed with a single paragraph in mind and so anything we try to do will look broken in at least one of the contexts.

**Comment by richiecroker** [comment]
we have others that we've used multiple paragraphs in, e.g. https://openprescribing.net/measure/seven_day_prescribing/

Too much text there to put in one paragraph.

**Comment by evansd** [comment]
OK. It looks broken here: https://openprescribing.net/measure/seven_day_prescribing/all-england/

**Comment by richiecroker** [comment]
is that possibly due to the fact that we've not put </p> in consistently.  I'm sure I spoke to someone about this when we did it, but maybe not.

**Comment by richiecroker** [comment]
Just realised there's no <p> on the first paragraph, maybe that's why it's broken there.  Shall I add one in and see what happens?

**Comment by evansd** [comment]
Sadly that will just make it even more broken :( There's literally no way to do what you want to do correctly given how things are set up. But if you're happy for it to look a bit weird in some contexts then what you originally had with the single `<p>` tag is probably the least worst option. Sorry for leading you round the houses!

**Comment by richiecroker** [comment]
My view is that it's better to have readable content in most contexts, even if a bit broken in some, rather than having one massive block of text which is somewhat more indigestible.  I'll try and raise it tomorrow to see what others think.

**Comment by richiecroker** [comment]
Also amused by me typing `<p>` in here and it just adding a paragraph!

**Comment by evansd** [comment]
I've made an issue to fix this properly. Just sticking that `<p>` back in is fine for now (I'll do it as I need to deploy that change manually anyway).

**Pull request merged**
