### PR TITLE
Update hospitals.html

### PR DESCRIPTION
**Pull request by richiecroker**
Add rx-info hyperlink

### CODE REVIEW

**Review by speed-vm — CHANGES_REQUESTED** [review]
Rich, needs to be this link, https://www.rx-info.co.uk not https://www.rx-info.co.uk/Rx-Info

**Comment by richiecroker** [comment]
weird @speed-vm i copied and pasted from the site.  Still, fixed now.

**Review by richiecroker — COMMENTED** [review]
fixed

**Review by speed-vm — APPROVED** [review]
Thanks

**Pull request merged**
