### PR TITLE
Misc measures bundle

### PR DESCRIPTION
**Pull request by sebbacon**

### CODE REVIEW

**Comment by sebbacon** [comment]
Run on deploy:

```sh
./manage.py import_measures --measure=ktt12_diabetes_insulin,ktt9_cephalosporins,lptramadolpara,other_lipid_modifying_drugs,sildenafil
echo "DELETE FROM frontend_measureglobal WHERE id IN ('ktt3_lipid_modifying_drugs', 'statins'); DELETE FROM frontend_measure WHERE measure_id IN ('ktt3_lipid_modifying_drugs', 'statins'); DELETE FROM frontend_measurevalue WHERE measure_id IN ('ktt3_lipid_modifying_drugs', 'statins')" | ./manage.py dbshell --settings=openprescribing.settings.production

```
What needs reviewing once I've deployed to staging:

@HelenCEBM:

* [ ] All titles, descriptions, why it matters

@brianmackenna:

* Data definition and data charts of:
  * [ ] ktt12_diabetes_insulin (just reformatting of SQL, shouldn't have changed)
  * [ ] ktt9_cephalosporins (just reformatting of SQL, shouldn't have changed)
  * [ ] lptramadolpara (had new BNF code added)
  * [ ] other_lipid_modifying_drugs (brand new)
  * [ ] sildenafil (brand new)

**Comment by evansd** [comment]
The full, corrected, list of commands to be run on deployment is:
```sh
./manage.py import_measures --measure=ktt12_diabetes_insulin,ktt9_cephalosporins,lptramadolpara,other_lipid_modifying_drugs,sildenafil

./manage.py import_measures --definition_only --measure=ace,arb,bdzadq,bdzper1000,ciclosporin,coproxamol,desogestrel,diltiazem,dipyridamole,doacs,fungal,glaucoma,glutenfree,icsdose,keppra,ktt12_diabetes_insulin,ktt13_nsaids_ibuprofen,ktt9_antibiotics,ktt9_cephalosporins,ktt9_cephalosporins_star,ktt9_uti_antibiotics,lpcoprox,lpdosulepin,lpdoxazosin,lpfentanylir,lpglucosamine,lphomeopathy,lplidocaine,lpliothyronine,lplutein,lpomega3,lpoxycodone,lpperindopril,lprubefacients,lptadalafil,lptramadolpara,lptravelvacs,lptrimipramine,lpzomnibus,lyrica,methotrexate,nebivolol,opioidome,opioidper1000,opioidspercent,other_lipid_modifying_drugs,ppidose,ppi,pregabalin,pregabalinmg,saba,sildenafil,silver,solublepara,statinintensity,tamoxifen,tramadol,trimethoprim,vitb

echo "DELETE FROM frontend_measureglobal WHERE measure_id IN ('ktt3_lipid_modifying_drugs', 'statins'); DELETE FROM frontend_measure WHERE id IN ('ktt3_lipid_modifying_drugs', 'statins'); DELETE FROM frontend_measurevalue WHERE measure_id IN ('ktt3_lipid_modifying_drugs', 'statins')" | ./manage.py dbshell
```

**Comment by evansd** [comment]
To whoever ends up merging this, can I suggest selecting "Squash and merge" so we don't end up with a history full of tiny edits.

**Comment by sebbacon** [comment]
The full, corrected again, list of commands to be run on deployment is:


```sh
./manage.py import_measures --measure=bdzadq,bdzper1000,ktt12_diabetes_insulin,ktt9_cephalosporins,lptramadolpara,other_lipid_modifying_drugs,sildenafil

./manage.py import_measures --definition_only --measure=ace,arb,ciclosporin,coproxamol,desogestrel,diltiazem,dipyridamole,doacs,fungal,glaucoma,glutenfree,icsdose,keppra,ktt12_diabetes_insulin,ktt13_nsaids_ibuprofen,ktt9_antibiotics,ktt9_cephalosporins,ktt9_cephalosporins_star,ktt9_uti_antibiotics,lpcoprox,lpdosulepin,lpdoxazosin,lpfentanylir,lpglucosamine,lphomeopathy,lplidocaine,lpliothyronine,lplutein,lpomega3,lpoxycodone,lpperindopril,lprubefacients,lptadalafil,lptramadolpara,lptravelvacs,lptrimipramine,lpzomnibus,lyrica,methotrexate,nebivolol,opioidome,opioidper1000,opioidspercent,other_lipid_modifying_drugs,ppidose,ppi,pregabalin,pregabalinmg,saba,sildenafil,silver,solublepara,statinintensity,tamoxifen,tramadol,trimethoprim,vitb

echo "DELETE FROM frontend_measureglobal WHERE measure_id IN ('ktt3_lipid_modifying_drugs', 'statins', 'quetiapine'); DELETE FROM frontend_measure WHERE id IN ('ktt3_lipid_modifying_drugs', 'statins', 'quetiapine'); DELETE FROM frontend_measurevalue WHERE measure_id IN ('ktt3_lipid_modifying_drugs', 'statins', 'quetiapine')" | ./manage.py dbshell
```

**Pull request merged**
