### PR TITLE
Fix fetch_and_import_drug_tariff

### LINKED ISSUE #733: Importing tariff data is failing
```
$ python manage.py fetch_and_import_drug_tariff --settings=openprescribing.settings.production
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/dmd/management/commands/fetch_and_import_drug_tariff.py", line 64, in handle
    import_month(xls_file, date)
  File "/webapps/openprescribing/openprescribing/dmd/management/commands/fetch_and_import_drug_tariff.py", line 90, in import_month
    product_id=get_product_id(d['vmpp snomed code']),
  File "/webapps/openprescribing/openprescribing/dmd/management/commands/fetch_and_import_drug_tariff.py", line 113, in get_product_id
    vpid = DMDVmpp.objects.get(pk=vmpp).vpid
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
dmd.models.DoesNotExist: DMDVmpp matching query does not exist.
```

### PR DESCRIPTION
**Pull request by inglesp**
Fixes #733.

### CODE REVIEW

**Comment by sebbacon** [comment]
Should I be reviewing this?

**Comment by inglesp** [comment]
Yes please.

**Comment by inglesp** [comment]
1. Because Pandas sometimes casts VMPP IDs to floats (see #733).
2. Because the default error message (eg `DoesNotExist: DMDProduct matching query does not exist.`) is not very helpful.

**Comment by sebbacon** [comment]
Great, all good!

**Pull request merged**
