### PR TITLE
Don't reference real measure in test

### PR DESCRIPTION
**Pull request by inglesp**
The deogestrel measure is going away.  All this test has to do is make check that some measure objects are created.

### CODE REVIEW

**Review by a-d-brown — APPROVED** [review]

**Comment by evansd** [comment]
Did I misunderstand this section of the test here (as is quite possible)?
https://github.com/ebmdatalab/openprescribing/blob/09a18cf587dc04b4ec6f40d9a693b1b79cb13157/openprescribing/frontend/tests/commands/test_import_measures.py#L65-L85

That looks like it's referencing a real measure as well.

**Comment by evansd** [comment]
Great, sorry for the noise!

**Comment by richiecroker** [comment]
#4489 is still failing though: https://github.com/ebmdatalab/openprescribing/actions/runs/7184392384/job/19567016519

**Comment by inglesp** [comment]
#4489 was failing because it didn't have this fix.  It does now, and is now green.

Sorry, should've thought of this!

**Pull request merged**
