### PR TITLE
Amend measure  lpzomnibus

### PR DESCRIPTION
**Pull request by richiecroker**
Removed tadalafil from SQL, updated hyperlink, and changed denominator calculation.

### CODE REVIEW

**Review by speed-vm — CHANGES_REQUESTED** [review]
@richiecroker should it say items for the hyperlink rather than areas to be consistent with Guidance doc?

**Comment by richiecroker** [comment]
@speed-vm items might get a little bit lost, as it can mean two things.  How about "therapeutic areas"

**Comment by speed-vm** [comment]
That maybe sounds more like asthma, or hypertension. What about medications or something to qualify items - Prescription items.

Items is in the title of the nearly all of the low priority measures though so might need to think whether want to change all?

**Comment by richiecroker** [comment]
Items is the name of the NHSE document, so we wouldn't want to change those!  Let's just go with items.

**Review by speed-vm — APPROVED** [review]
Yes, looks good

**Review by richiecroker — COMMENTED** [review]
all ok

**Review by richiecroker — COMMENTED** [review]
all ok

**Pull request merged**
