### PR TITLE
Helpful text additions

### PR DESCRIPTION
**Pull request by sebbacon**
search
home

Closes issue #211

### CODE REVIEW

**Comment by annapowellsmith** [comment]
Nice! The blue is a great improvement. Let's make the alert box on analyse blue too. 

Please could we tweak the margins around the front page alert box so it is the same top and bottom? (or if you put the branch on staging then I will fiddle with it and get the exact numbers)

**Comment by sebbacon** [comment]
done (force-pushed)

margin

**Comment by annapowellsmith** [comment]
Excellent! I would like to find a way to make this whole page friendlier and less busy, but I think we can punt that till our

**Comment by annapowellsmith** [comment]
Broken Travis, sad times :( https://twitter.com/andyhume/status/784404732483923968

**Comment by annapowellsmith** [comment]
:thumbsup:

**Pull request merged**
