### PR TITLE
Change support email address throughout

### LINKED ISSUE #172: Make all contact links go to the Google group
We have "contact us" links in the footer, which should use the Google group for consistency. 

As should the link on the about page, and any other mentions of mail@openprescribing.

Also, I think we should lose the mail link on the analyse page, since that page now has 4 separate ways to contact us!

### PR DESCRIPTION
**Pull request by sebbacon**
Fixes #172

### CODE REVIEW

**Comment by annapowellsmith** [comment]
Also worth changing `CONTRIBUTING.md` and `settings/base.py`, for the record?

**Comment by sebbacon** [comment]
What in `settings/base.py` needs changing?

**Comment by annapowellsmith** [comment]
Here! https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/openprescribing/settings/base.py#L241

**Comment by sebbacon** [comment]
Thanks, thought you might be referring to something else

**Comment by annapowellsmith** [comment]
Yay, if you rebase I will merge 🐺

**Pull request merged**
