### PR TITLE
New measure fluoroquinolone items per 1000 registered patients

### PR DESCRIPTION
**Pull request by chrisjwood16**
https://openprescribing.net/measure/preview_fluoroquinolones_list/

### CODE REVIEW

**Comment by chrisjwood16** [comment]
@speed-vm my initial thought process was it's easier to keep to specifying oral route so non-systemic formulations aren't picked up (and likely very limited prescribing of IV/inhaled).
On looking a bit further:
1) there are no non-systemic in that chapter.
2) very minimal prescribing of IV/inhaled (approx 140 items over 6 years)

I've had another think through and perhaps the easiest option (in terms of easy of explaining) - is to include all systemic formulations. I've then just added the word systemic into the description to clarify.

**Comment by speed-vm** [comment]
Looks good to me. Is consistent with Safety alert

**Review by speed-vm — APPROVED** [review]
Looks good to me

**Comment by chrisjwood16** [comment]
@richiecroker please can you merge this when you have chance

**Review by richiecroker — APPROVED** [review]

**Pull request merged**
